import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Test App A',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-full ${inter.className}`}>
        <div className='flex h-full'>
          <Sidebar />
          <div className='flex-grow'>{children}</div>
        </div>
      </body>
    </html>
  )
}
